services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:9000"
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: api_resume_builder
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
